### PR TITLE
Swap out "io.takari" maven wrapper for "org.apache"

### PR DESCRIPTION
**Pull request by MikAoJk**
## Description
Use org apache maven wrapper instead of io.takari

## Motivation and Context
Maintained maven wrapper

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by Semernitskaya** [comment]
Checked PR: suggested script matches script autogenerated for maven wrapper, can be safely included into project 👍@MikAoJk thank you for your contribution

**Review by Semernitskaya — APPROVED** [review]

**Comment by MikAoJk** [comment]
Sure, the commit should be signed now

**Comment by fatroom** [comment]
👍

**Comment by fatroom** [comment]
Thank you for the contribution!

**Pull request merged**
